version: '3'

networks:
  sso:
    driver: ${NETWORKS_DRIVER}

services:
  openldap:
    build:
      context: ./openldap
    environment:
      - LDAP_ORGANISATION=My Company
      - LDAP_DOMAIN=My Company
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
      - "636:636"
    networks:
      - sso


  phpldapadmin:
    build:
      context: ./phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "6443:443"
    depends_on:
      - openldap
    networks:
      - sso


#  simplesaml:
#    build:
#      context: ./simplesaml
#    networks:
#      - sso